[2025-07-06T00:19:15.736+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-06T00:19:15.792+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_model_retraining.retrain_model manual__2025-07-06T00:19:11.867070+00:00 [queued]>
[2025-07-06T00:19:15.804+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_model_retraining.retrain_model manual__2025-07-06T00:19:11.867070+00:00 [queued]>
[2025-07-06T00:19:15.804+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-06T00:19:15.819+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): retrain_model> on 2025-07-06 00:19:11.867070+00:00
[2025-07-06T00:19:15.837+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=198) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-06T00:19:15.838+0000] {standard_task_runner.py:63} INFO - Started process 204 to run task
[2025-07-06T00:19:15.837+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weekly_model_retraining', 'retrain_model', 'manual__2025-07-06T00:19:11.867070+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/retraining_dag.py', '--cfg-path', '/tmp/tmpjxv4ulcg']
[2025-07-06T00:19:15.842+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask retrain_model
[2025-07-06T00:19:15.861+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T00:19:15.900+0000] {task_command.py:426} INFO - Running <TaskInstance: weekly_model_retraining.retrain_model manual__2025-07-06T00:19:11.867070+00:00 [running]> on host 99d948e6500d
[2025-07-06T00:19:15.987+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rajat' AIRFLOW_CTX_DAG_ID='weekly_model_retraining' AIRFLOW_CTX_TASK_ID='retrain_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T00:19:11.867070+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T00:19:11.867070+00:00'
[2025-07-06T00:19:15.990+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-06T00:19:16.027+0000] {logging_mixin.py:188} INFO - [INFO] Found latest timestamp: 2025-07-04-15
[2025-07-06T00:19:16.027+0000] {logging_mixin.py:188} INFO - [INFO] Starting model training...
[2025-07-06T00:19:16.204+0000] {logging_mixin.py:188} WARNING - 2025/07/06 00:19:16 INFO mlflow.tracking.fluent: Experiment with name 'anomaly_detection_github' does not exist. Creating a new experiment.
[2025-07-06T00:19:16.297+0000] {logging_mixin.py:188} WARNING - 2025/07/06 00:19:16 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-07-06T00:19:17.628+0000] {logging_mixin.py:188} WARNING - 2025/07/06 00:19:17 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
[2025-07-06T00:19:25.805+0000] {logging_mixin.py:188} WARNING - 2025/07/06 00:19:25 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-07-06T00:19:26.208+0000] {logging_mixin.py:188} WARNING - Registered model 'github-anomaly-isolation-forest' already exists. Creating a new version of this model...
[2025-07-06T00:19:26.291+0000] {logging_mixin.py:188} WARNING - 2025/07/06 00:19:26 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: github-anomaly-isolation-forest, version 2
[2025-07-06T00:19:26.291+0000] {logging_mixin.py:188} WARNING - Created version '2' of model 'github-anomaly-isolation-forest'.
[2025-07-06T00:19:26.374+0000] {logging_mixin.py:188} INFO -        actor  anomaly_score  anomaly
0       0-st       0.293130    False
1  00-uno-00       0.293130    False
2  0001Moksh       0.271735    False
3     0047ol       0.293130    False
4   006-Ekta       0.293130    False
[2025-07-06T00:19:26.391+0000] {logging_mixin.py:188} INFO - üèÉ View run fortunate-turtle-787 at: http://mlflow-server:5000/#/experiments/1/runs/6ab940d5f60b46dc8077e397bf9c445b
[2025-07-06T00:19:26.391+0000] {logging_mixin.py:188} INFO - üß™ View experiment at: http://mlflow-server:5000/#/experiments/1
[2025-07-06T00:19:26.426+0000] {logging_mixin.py:188} INFO - [INFO] Training completed successfully.
[2025-07-06T00:19:26.427+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-06T00:19:26.427+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-06T00:19:26.436+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weekly_model_retraining, task_id=retrain_model, run_id=manual__2025-07-06T00:19:11.867070+00:00, execution_date=20250706T001911, start_date=20250706T001915, end_date=20250706T001926
[2025-07-06T00:19:26.489+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-06T00:19:26.500+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-06T00:19:26.501+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
